// List of all 275 constituencies in Ghana organized by region
export const ghanaConstituencies = [
  // Greater Accra Region
  'Ablekuma Central',
  'Ablekuma North',
  'Ablekuma South',
  'Ablekuma West',
  'Ada',
  'Adentan',
  'Anyaa Sowutuom',
  'Ashaiman',
  'Ayawaso Central',
  'Ayawaso East',
  'Ayawaso North',
  'Ayawaso West Wuogon',
  'Bortianor Ngleshie Amanfro',
  'Domeabra Obom',
  'Korle Klottey',
  'Kpone Katamanso',
  'Krowor',
  'La Dadekotopon',
  'La Nkwantanang Madina',
  'Ledzokuku',
  'Odododiodio',
  'Okaikwei Central',
  'Okaikwei North',
  'Shai Osudoku',
  'Tema Central',
  'Tema East',
  'Tema West',
  'Weija Gbawe',
  
  // Ashanti Region
  'Adansi Asokwa',
  'Afigya Kwabre North',
  'Afigya Kwabre South',
  'Afigya Sekyere East',
  'Ahafo Ano North',
  'Ahafo Ano South East',
  'Ahafo Ano South West',
  'Akrofuom',
  'Atwima Kwanwoma',
  'Atwima Mponua',
  'Atwima Nwabiagya North',
  'Atwima Nwabiagya South',
  'Asante Akim Central',
  'Asante Akim North',
  'Asante Akim South',
  'Asawase',
  'Asokore Mampong',
  'Asokwa',
  'Bantama',
  'Bekwai',
  'Bosome Freho',
  'Bosomtwe',
  'Ejisu',
  'Ejura Sekyedumase',
  'Fomena',
  'Juaben',
  'Kwabre East',
  'Kwadaso',
  'Mampong',
  'Manso Adubia',
  'Manso Nkwanta',
  'New Edubiase',
  'Nhyiaeso',
  'Nsuta Kwamang Beposo',
  'Obuasi East',
  'Obuasi West',
  'Odotobri',
  'Oforikrom',
  'Old Tafo',
  'Suame',
  'Subin',
  
  // Western Region
  'Ahanta West',
  'Amenfi Central',
  'Amenfi East',
  'Amenfi West',
  'Effia',
  'Ellembelle',
  'Evalue Ajomoro Gwira',
  'Kwesimintsim',
  'Mpohor',
  'Prestea Huni Valley',
  'Sekondi',
  'Shama',
  'Takoradi',
  'Tarkwa Nsuaem',
  'Wassa East',
  
  // Western North Region
  'Aowin',
  'Bodi',
  'Bia East',
  'Bia West',
  'Bibiani Anhwiaso Bekwai',
  'Juaboso',
  'Sefwi Akontombra',
  'Sefwi Wiawso',
  'Suaman',
  
  // Central Region
  'Abura Asebu Kwamankese',
  'Agona East',
  'Agona West',
  'Ajumako Enyan Esiam',
  'Asikuma Odoben Brakwa',
  'Assin Central',
  'Assin North',
  'Assin South',
  'Awutu Senya East',
  'Awutu Senya West',
  'Cape Coast North',
  'Cape Coast South',
  'Ekumfi',
  'Gomoa Central',
  'Gomoa East',
  'Gomoa West',
  'Hemang Lower Denkyira',
  'Komenda Edina Eguafo Abirem',
  'Mfantseman',
  'Twifo Atti Morkwa',
  'Upper Denkyira East',
  'Upper Denkyira West',
  
  // Eastern Region
  'Abetifi',
  'Abirem',
  'Abuakwa North',
  'Abuakwa South',
  'Afram Plains North',
  'Afram Plains South',
  'Akim Achiase',
  'Akim Oda',
  'Akim Swedru',
  'Akuapem North',
  'Akuapem South',
  'Akyemansa',
  'Atiwa East',
  'Atiwa West',
  'Ayensuano',
  'Birim Central',
  'Birim North',
  'Birim South',
  'Denkyembour',
  'Fanteakwa North',
  'Fanteakwa South',
  'Kade',
  'Lower Manya Krobo',
  'Lower West Akim',
  'Mpraeso',
  'New Juaben North',
  'New Juaben South',
  'Nkawkaw',
  'Nsawam Adoagyiri',
  'Okere',
  'Okoawman',
  'Suhum',
  'Upper Manya Krobo',
  'Upper West Akim',
  'Yilo Krobo',
  
  // Volta Region
  'Adaklu',
  'Agotime Ziope',
  'Akatsi North',
  'Akatsi South',
  'Anlo',
  'Central Tongu',
  'Ho Central',
  'Ho West',
  'Hohoe',
  'Keta',
  'Ketu North',
  'Ketu South',
  'Kpando',
  'North Dayi',
  'North Tongu',
  'South Dayi',
  'South Tongu',
  
  // Oti Region
  'Akan',
  'Biakoye',
  'Buem',
  'Guan',
  'Krachi East',
  'Krachi Nchumuru',
  'Krachi West',
  'Nkwanta North',
  'Nkwanta South',
  
  // Bono Region
  'Banda',
  'Berekum East',
  'Berekum West',
  'Dormaa Central',
  'Dormaa East',
  'Dormaa West',
  'Jaman North',
  'Jaman South',
  'Sunyani East',
  'Sunyani West',
  'Tain',
  'Wenchi',
  
  // Bono East Region
  'Atebubu Amantin',
  'Kintampo North',
  'Kintampo South',
  'Nkoranza North',
  'Nkoranza South',
  'Pru East',
  'Pru West',
  'Sene East',
  'Sene West',
  'Techiman North',
  'Techiman South',
  
  // Ahafo Region
  'Asunafo North',
  'Asunafo South',
  'Asutifi North',
  'Asutifi South',
  'Tano North',
  'Tano South',
  
  // Northern Region
  'Karaga',
  'Kpandai',
  'Mion',
  'Nanton',
  'Saboba',
  'Savelugu',
  'Tamale Central',
  'Tamale North',
  'Tamale South',
  'Tatale Sanguli',
  'Tolon',
  'Yendi',
  'Zabzugu',
  
  // Savannah Region
  'Bole Bamboi',
  'Damongo',
  'Daboya Mankarigu',
  'Salaga North',
  'Salaga South',
  'Sawla Tuna Kalba',
  'Yapei Kusawgu',
  
  // North East Region
  'Bunkpurugu',
  'Chereponi',
  'Nalerigu Gambaga',
  'Walewale',
  'Yunyoo',
  'Yagaba Kubori',
  
  // Upper East Region
  'Bawku Central',
  'Bawku West',
  'Binduri',
  'Bolgatanga Central',
  'Bolgatanga East',
  'Bongo',
  'Builsa North',
  'Builsa South',
  'Chiana Paga',
  'Garu',
  'Nabdam',
  'Navrongo Central',
  'Pusiga',
  'Talensi',
  'Tempane',
  'Zebilla',
  
  // Upper West Region
  'Daffiama Bussie Issa',
  'Jirapa',
  'Lambussie',
  'Lawra',
  'Nadowli Kaleo',
  'Nandom',
  'Sissala East',
  'Sissala West',
  'Wa Central',
  'Wa East',
  'Wa West',
].sort();

export const gimpaSchools = [
  'School of Business',
  'School of Public Service and Governance',
  'School of Technology',
  'School of Law',
  'Faculty of Finance and Management Studies',
  'Faculty of Academic Affairs and Research',
];

export const levelOptions = [
  '100',
  '200',
  '300',
  '400',
  'Post Graduate',
];
